services:
  downloader:
    image: downloader:latest
    container_name: downloader
    ports:
      - 6080:6080
      - 5901:5901
    shm_size: 2g
    build:
      context: .
    # command: 'python3 download.py'
